### ISSUE TITLE
Critical: Game Activity: Single Task

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#100]
Now, only one "Game Activity" can be displayed in app
each time after going to different screens - only one Game activity displayed

**Comment by Serduk** [comment]
Fixed.
see row 40
https://github.com/Serduk/whatWhereWhen/blob/master/app/src/main/AndroidManifest.xml

what that mean: after each come to this activity from different source -> it will be stay 1 veersion of this activity. we will not create any new activity with this type

**Comment by inndunas** [comment]
@Serduk checked on 1.2.1
