### ISSUE TITLE
MAJOR: Merge Questions list activity and Questions in one activity

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#105]
Merge Both activity to one activity
Move functionality with questions uploading to one button "+" bellow right
Sync questions with server -> should be deleted and it should work as foregroundservice

**Comment by Serduk** [comment]
should be implemented already existing model: QuestionsListViewModel

**Comment by Serduk** [comment]
Implement FAB:
https://developer.android.com/reference/android/support/design/widget/FloatingActionButton

**Comment by Serduk** [comment]
Implemented in 1.3.0
When you go to questions list: you will see button "+" with possibility to upload questions

**Comment by inndunas** [comment]
@Serduk checked on 1.3.1, button works correct
