### ISSUE TITLE
CRITICAL: Game Activity: app folding during the game leads to losing current game results

### ISSUE THREAD

**Issue by inndunas** [Serduk/whatWhereWhen#111]
**Descriptions:**
app folding during the game leads to losing current game results
**Environment:**
1.2.1 build
**Preconditions:**
app launched
**STR:**
1. start a new game (any random or custom)
2. answer for 2 questions
3. fold the app (go to main screen of your phone)
4. come back to app

**Actual result:**
current game results are lost, screen with new game preconditions is shown
**Expected result:**
current game results are saved, user can continue current game
**Attachments:**
screen record of this problem - 
https://drive.google.com/file/d/1-mLEbdfw0d1Cyk_6nUe4dgqasloWFavs/view?usp=sharing

**UPD:** 
the same actual result in case of:
- answering incoming call;
- opening incoming message;
- opening any notification from another apps

**Comment by Serduk** [comment]
Fixed in 1.3.0
Now after collapsing app -> all data loading back

**Comment by inndunas** [comment]
@Serduk checked on 1.3.1, fixed
