### ISSUE TITLE
MAJOR: Questions list activity: move buttons to snackbar

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#112]
1. Go to questions list
2. Instead 3 buttons bellow -> should be displayed 1 button which call like "I want something do with my selected questions"
3. After tapping on this button should be displayed 3 buttons bellow (delete, start game, clear all)

**Examples:**
https://spin.atomicobject.com/2017/07/10/android-snackbar-tutorial/
https://stackoverflow.com/questions/32453946/how-to-customize-snackbars-layout
https://www.journaldev.com/10324/android-snackbar-example-tutorial
https://www.androidhive.info/2015/09/android-material-design-snackbar-example/

**Comment by Serduk** [comment]
should be implemented like dialog:
bottomsheetdialog
http://android-er.blogspot.com/2016/06/bottomsheetdialog-example.html
or snackbar:
https://stackoverflow.com/questions/41224019/can-we-perform-2-different-actions-in-snack-bar-at-a-time-in-android

**Comment by Serduk** [comment]
replaced with bottom dialog:
![image](https://user-images.githubusercontent.com/2543139/43544614-3140e38a-95dc-11e8-94b7-a09ec5920995.png)

![image](https://user-images.githubusercontent.com/2543139/43544621-37fca57e-95dc-11e8-8110-80e6ccfdd200.png)

**Comment by Serduk** [comment]
Latest commit 201452d

**Comment by inndunas** [comment]
@Serduk checked on 1.3.1, buttons work correct
