### ISSUE TITLE
CRITICAL: Game activity: folding app with opened game preconditions screen leads to start new game from 2nd question

### ISSUE THREAD

**Issue by inndunas** [Serduk/whatWhereWhen#114]
**Descriptions:**  
Folding app with opened game preconditions screen leads to start new game from 2nd question. 
**Environment:**
Build 1.2.1
**Preconditions:**
App is launched

**STR:**
1. Tap on 'Start game'
2. Fold app with opened game preconditions screen
3. Come back to app
4. Tap on 'Start random game'
5. Tap on 'Start random game' again

**Actual result:**
1. After the first tap on 'Start random game' game didnt started, but on the grayed game screen count of questions was changed to 1 of 36.
2. After the second tap on 'Start random game' game was started from 2nd question (count of questions is 2 of 36)

**Expected result:**
After the first tap on 'Start random game' game was started, count of questions is 1 of 36.
Attachments:
link to screen recording - https://drive.google.com/file/d/11HedLAUpYJL_fceGjS-i-A0GBe-LswIz/view?usp=sharing

**Comment by Serduk** [comment]
Fixed in 1.3.0

**Comment by inndunas** [comment]
@Serduk checked in 1.3.1, fixed
