### ISSUE TITLE
LOW: Game activity: Add condition for check question, is already loaded for custom game or for fast

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#15]
Game activity: Add condition for check question, is already loaded for custom game or for fast

**Comment by Serduk** [comment]
Should be implemented after https://github.com/Serduk/whatWhereWhen/issues/26

Alert will be shown, and should be some spinner in up, while data is loaad

**Comment by Serduk** [comment]
fixed in 0.0.4
@inndunas , verify it, Please.

How i fix it: 
User tap on Button "start game" in alert
Alert has refreshed and shown again

Code:
`                        if (questionsList.isEmpty()) {
                            Toast.makeText(GameActivity.this,
                                    "Game can't be started. Please Create Question List",
                                    Toast.LENGTH_LONG).show();
                            startGameDialog();`

**Comment by inndunas** [comment]
@Serduk 
checked in 0.0.4 build
