### ISSUE TITLE
CRITICAL: OnStop/OnPause: Current state should be saved

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#18]
Add conditions for OnStop/OnPause
All current states should be saved

**Comment by Serduk** [comment]
@inndunas ,
Please, retest this issue.
We should check next steps:

Pre-Conditions:
* app started
* Questions uploaded
* give answer on some question (change details in rating, and # of answered question)

Check:

- [ ] Take income call
- [ ] Receive message
- [ ] Lock screen
- [ ] Collapse app to tray. open any another. Switch to WWW app
- [ ] Collapse app to tray. lock phone

**Comment by inndunas** [comment]
@Serduk 
all these conditions were checked in 0.0.4 build

**Comment by Serduk** [comment]
@inndunas 
Everything ok, and fixed?
Problem is not reproducible?
You already check all of this 5 cases? if yes -> please, mark them as checked (Click on them)

**Comment by inndunas** [comment]
@Serduk 
everything fixed, all 5 cases are marked as checked
