### ISSUE TITLE
Critical: Answer: user can change his own rating on "non quest" screen and after last question

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#2]
**STR:**
1. Open game activity
2. Choose wrong or correct answer

**Actual Result:**
Rating increased and deceased

This bug actual for first step, and on last, were user see "all questions is ended'

**Comment by Serduk** [comment]
hey, @inndunas 

This issue is duplicate of tickets bellow

Should be fixed in: 
https://github.com/Serduk/whatWhereWhen/issues/19
https://github.com/Serduk/whatWhereWhen/issues/20

Build:
0.0.4

**Comment by inndunas** [comment]
@Serduk 
was checked in 0.0.4 build
