### ISSUE TITLE
Major: Game Activity: add % of Win / Lose games

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#21]
add new feature:
We should display % of win and lose of current game.
When all questions will be completed - % should be displayed in final alert

**Comment by Serduk** [comment]
Fixed in 0.0.7

`
        if (0 < gameSize) {
            winPercent = win * 100 / gameSize;
            losePercent = 100 - winPercent;
        }

        winPercentStr = "Percent of Win is: " + winPercent + "\n"
                + "Percent of Lose is: " + losePercent;`

`        dialogLastQuestionPlayed.setMessage("Total played " + gameInfoHeader + "\n" + gameScore
                + "\n" + winPercentStr);`

**Comment by Serduk** [comment]
master 4f5ccd9]

**Comment by inndunas** [comment]
@Serduk 
checked in 0.0.7 build
