### ISSUE TITLE
Major: Game Activity: Replace timer format

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#22]
Replace timer format from threadsleep to correct timer libs

this code should be optimized:

`    private void runTimer() {

        /*
         * isWasRunning MARKED AS FALSE
         * REASON: AFTER EACH START QUESTION (START-STOP) WE SHOULD RUN TIMER FROM 60
         * */
        secondsLeft = seconds;

        final Handler handler = new Handler();

        handler.post(new Runnable() {
            @Override
            public void run() {
                System.out.println(secondsLeft);

                if (isWasRunning) {
                    timeLeft = timeResult + secondsLeft;
                    time.setText(timeLeft);
                    if (!isTimesUp) {
                        secondsLeft--;
                    }

                    if (secondsLeft == 0) {
                        time.setText(R.string.time_is_up);
                        secondsLeft = seconds;
                        isTimesUp = true;
                    }

                    handler.postDelayed(this, 1000);
                }
            }
        });
    }`

**Comment by Serduk** [comment]
Examples: 

`up vote
68
down vote
accepted
You'll find one in

http://commons.apache.org/lang/

It's called

org.apache.commons.lang.time.StopWatch
But it roughly does the same as yours. If you're in for more precision, use

System.nanoTime()`

` public class StopWatch {

  private long startTime = 0;
  private long stopTime = 0;
  private boolean running = false;


  public void start() {
    this.startTime = System.currentTimeMillis();
    this.running = true;
  }


  public void stop() {
    this.stopTime = System.currentTimeMillis();
    this.running = false;
  }


  //elaspsed time in milliseconds
  public long getElapsedTime() {
    long elapsed;
    if (running) {
      elapsed = (System.currentTimeMillis() - startTime);
    } else {
      elapsed = (stopTime - startTime);
    }
    return elapsed;
  }


  //elaspsed time in seconds
  public long getElapsedTimeSecs() {
    long elapsed;
    if (running) {
      elapsed = ((System.currentTimeMillis() - startTime) / 1000);
    } else {
      elapsed = ((stopTime - startTime) / 1000);
    }
    return elapsed;
  }
} `

**Comment by Serduk** [comment]
Chronometer
https://abhiandroid.com/ui/chronometer

**Comment by Serduk** [comment]
Replaced and implemented.
Already used in build

How you can check it:
* Displayed in code in rows: 179-199
https://github.com/Serduk/whatWhereWhen/blob/master/app/src/main/java/com/sserdiuk/whatwherewhen/GameActivity.java
* Timer should work correctly (start, stop, tick)

**Comment by inndunas** [comment]
checked in 1.2.1
