### ISSUE TITLE
Major: File Reader request: move to app launch

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#24]
When app go start:
1. app should request read files permissisons
2. Add app premissioon on qustion list

**Comment by Serduk** [comment]
hey, @inndunas .
Fixed in 0.0.5 build

Please verify it, after 0.0.5 release

**Comment by Serduk** [comment]
one of STR for check it:
1. Launch app

Actual: Should be displayed popup for request permissions
If customer confirm access to his external storage -> in future this popup shouldn't be displayed

If permissions not granted -> this popup should be displayed on each app starting

**Comment by inndunas** [comment]
@Serduk 
checked in 0.0.5 build
