### ISSUE TITLE
Critical: Upload questions without app permission: first launch: show successfull uploading for not uploaded files

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#25]
Pre-condition:
1. first start app
2. read external files not granted

STR:
1. upload some correct file

actual result:
displayed popup about permission not granted
displayed toast with message: successfull upload file
File not uploaded

Expected result:
message about successful uploading shouldn't be displayed

**Comment by inndunas** [comment]
@Serduk 
checked in 0.0.5 build.
