### ISSUE TITLE
Critical: Game Activity: first launch: display alert with "ready to game?"

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#26]
Story:
1. User open game activity
2. Game activity display alert with 2 buttons:
1.. set questionList
2.. start game

* If user tap on "set question list" -> should be opened Questions activity
* If user tap on "start game" -> should be displayed basic game activity with 1 of question queue list
** If user don't have any uploaded questoin in DB -> "start game" should be inactive

**Comment by Serduk** [comment]
@inndunas , should be fixed in 0.0.4
Verify it please

**Comment by inndunas** [comment]
@Serduk 
checked in 0.0.4 build
