### ISSUE TITLE
LOW: Create repo and move builds to hockeyApp

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#30]
LOW: Create repo and move builds to hockeyApp

In next -> we should install test builds from hockeyApp

**Comment by Serduk** [comment]
Done:
https://rink.hockeyapp.net/manage/apps/776910

**Comment by Serduk** [comment]
Now, all user which has access to the app can download this app from hockeyapp

**Comment by inndunas** [comment]
@Serduk great idea :)
