### ISSUE TITLE
NORMAL: Game Activity: antifraud notification:  displayed in wrong time after repeat rating improvement

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#31]
Message:
YOU CAN'T SELECT SAME ANSWER RESULT FEW TIMES

Pre-Condition:
upload questions
start game
give answer on one of the question

STR:
1. Tap on Answer
2. Rate as "correct answer"
3. Tap on "Answer"
3. Rate as "correct Answer"

**Actual restult:**
Notification YOU CAN'T SELECT SAME ANSWER RESULT FEW TIMES not displayed
This notification displayed only after tap on "answer" in 3rd time

**Comment by Serduk** [comment]
Hey, @inndunas 
Should be fixed in 0.0.4
Please verify it there

**Comment by inndunas** [comment]
@Serduk 
checked in 0.0.4 build
notification is displayed correctly
