### ISSUE TITLE
CRITICAL: Game activity: Non-working button "back" in start game menu

### ISSUE THREAD

**Issue by inndunas** [Serduk/whatWhereWhen#36]
**Descriptions:** 
Android button "back" does not work in start game menu.
**UPD:** incorrect work of button "back" started after going to questions activity: user has a cycle of coming back to main activity from question activity, user can not close the app using button "back". 

Problem is actual for Android 7.0, Samsung Galaxy S3 (2016).

**Environment:**
Build 0.0.4

**STR:**
1. Open application
2. Start new game
3. Press button "back"

**Actual result:**
Start game menu is still displayed

**Expected result:**
Main layuot is displayed

**Related issues:**
#45
#35 
#40 

variant for fixing:
launchMode

**Comment by Serduk** [comment]
partly fixed in #40

**Comment by inndunas** [comment]
@Serduk 
checked in 0.0.7 build
