### ISSUE TITLE
Major: Game played history: create new activity with game history information

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#37]
Major: Game played history: create new activity with game history information and statistic

Game History activity should be displayed in Main menu
After tap on him open new activity "Game History" which have table with game informtion

----------------------------------------------------------------------------------------------------
| user name | date of play | count of played questions in session | Win | Lose | Skipped | Win% |
----------------------------------------------------------------------------------------------------

- [x] Prepare entity Score commit a8ba7f078b4f5afcf33e2874c6f5d20ed9cedf2a
- [x] Prepare ScoreDao commit: 928ec02
- [x] Set queries which save data to db 5f265c0
- [x] Prepare activity for displaying data about questions 9129b88
- [x] Display results in activity 9451518 + 6099790 + 06bfa77
- [ ] Display detailed results about each game after tapping on results #80
- [ ] PlayedHistory: add highlighting for results #84

![1](https://user-images.githubusercontent.com/2543139/40301549-182eb4dc-5cf5-11e8-864e-9e849001ee75.jpeg)
![2](https://user-images.githubusercontent.com/2543139/40301550-184b1bb8-5cf5-11e8-89a5-200e78d97c7f.jpeg)
![3](https://user-images.githubusercontent.com/2543139/40301551-18655ca8-5cf5-11e8-9e6d-43d407642ab5.jpeg)

**Comment by Serduk** [comment]
Display detailed results about each game after tapping on results => should be released in another issue

**Comment by inndunas** [comment]
@Serduk checked in 1.2.0
