### ISSUE TITLE
Critical: Main activity: tap on system back button: display popup with exit confirmation

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#40]
Critical: Main activity: tap on system back button: display popup with exit confirmation

When user tap on system "back" button -> show popup with exit confirmation.

**Related issues:**
#45
#35 
#40 

variant for fixing:
launchMode

**Comment by Serduk** [comment]
Fixed in 0.0.5

**Comment by Serduk** [comment]
Problem still present

**Comment by Serduk** [comment]
master 4f5ccd9]

**Comment by inndunas** [comment]
@Serduk 
checked in 0.0.7 build
