### ISSUE TITLE
Critical: BE: optimize all listViews: get element ID -> add action for them

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#42]
Improve listViews layouts in main menu and questions list

**Now:**
We use hardcode for clicked elements (click on 1 elem, 2nd elem etc)

**Should be:**
Get id of clicked element -> use correct method for clicked element in switcher
This fix prevent missig on click, when we add new item to list in some middle place

**Comment by Serduk** [comment]
On of solving variant:
`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string-array name="planets_array">
        <item>Mercury</item>
        <item>Venus</item>
        <item>Earth</item>
        <item>Mars</item>
    </string-array>

    <string-array name="planets_array_values" translatable="false">
        <item>merc</item>
        <item>ven</item>
        <item>eart</item>
        <item>mars</item>
    </string-array>
</resources>`

Then populate the spinner with planets_array, and

`public void onItemSelected(AdapterView<?> parent, View view, 
        int pos, long id) {
    String value = getResources().getStringArray(R.array.planets_array_values)[pos];
}`

**Comment by Serduk** [comment]
Fixed in 0.0.8
how we can check it:
we should check all active views (buttons) on main screen and questions screen

**Comment by inndunas** [comment]
@Serduk 
checked in 0.0.9 build
