### ISSUE TITLE
Critical: BE: Add DB Migration to new version: Add new column: "selected question for current game"

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#43]
Add DB migration to version 2 add column with boolean is selected question for current game

In this column should be saved data about "is this question should be added to custom game?"

user story:
User open question list
User select some Question
User play custom game
 
in this custom game should be displayed all of this selected question

Related issues:
#8 
#9 
#10

**Comment by Serduk** [comment]
Fixed and implemented in 0.0.8 
How we can check it:
1. Go to questions list
2. Mark few questions in list (set checkbox true)
3. go back to previous screen or on any other
4. Go to question list. -> all selected questions from step 2 should be selected

============
5. Tap on "clear all custom question"
6. All question should be unselected
7. Go away and come back to question list screen -> all question should be unselected

**Comment by inndunas** [comment]
@Serduk 
checked in 0.0.9 build
