### ISSUE TITLE
Critical: Game Activity: Button back from question activity doesn't work

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#45]
@Inna -> create for me ticket which should manage back button from questions
if user don't select any game type and go to questions from game activity, and then press button back -> he should see Alert

**Related issues:**
#45
#35 
#40 

variant for fixing:
launchMode

**Comment by Serduk** [comment]
commit:
master 4f5ccd9]

**Comment by inndunas** [comment]
@Serduk 
cheched in 0.0.7 build. 
user see alert "no questions selected"
