### ISSUE TITLE
Critical: Question list: fix and fulfill all functionality of Questions layout

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#46]
**Questions List DB refactoring:**

- [x] add list of all questions (All questoion should be displayed in activity)
- [x] add checkBox should be played or not (For custom game)
- [ ] add selected question counter (in header. how much question already selected)

if checkbox selected or unselected -> create update query for DB. then this selected question will be played

all this query should work in background. and data update online

related to:
 #8 
#9 
#10 
#43

**Comment by Serduk** [comment]
hey, @inndunas 
this point: add selected question counter (in header. how much question already selected) I'll implement in another ticket #64 

How i see -> it's not trivial issue. so i need more time for implementation of this functional.
Will be fixed in next release.
At current time i was add mock https://monosnap.com/file/WQXO8wDgfcRVo0XOKqqPY0rSiCppXe

**Comment by Serduk** [comment]
All another points fixed in 0.0.8

**Comment by inndunas** [comment]
@Serduk 
points 1 and 2 were checked in 0.0.9 build
