### ISSUE TITLE
Major: Questions: create Upload and start game module

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#5]
Story:
1. go to Questions
2. add variant "choose questions and start game"
3. User upload his own questions
4. Game started automatically

questions choosed
Game Activity with latest uploaded question added

TODO:
should be extended from basic "question" activity.

**Comment by Serduk** [comment]
Commit with realization: c5c26f4

Fixed in 1.0.1

**Comment by inndunas** [comment]
@Serduk 
checked in 1.1.0 build
