### ISSUE TITLE
Critical: Question Details Activity: Create new activity

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#51]
Create new activity DetailsOfQuestionActivity

This activity should be opened after tap on some question in QuestionList activity.

User story:
User go to Questions
User open questions list #8 (Issue for this activity)
User tap on Question

Result:
DetailsOfQuestionActivity opened
insede of this activity next data:
1. Date of uploading
2. Question
3. Answer
4. Difficult

**Comment by Serduk** [comment]
How to get:
Go to questions => questions list => tap on any question there

**Comment by inndunas** [comment]
@Serduk 
checked in 0.0.7 build
