### ISSUE TITLE
Major: BE: refactoring of QuestionsListAdapter.

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#53]
https://github.com/Serduk/whatWhereWhen/blob/master/app/src/main/java/com/sserdiuk/whatwherewhen/QuestionsListAdapter.java

Remove DB calls from QuestionsListActivity. and use it just here in QuestionsListAdapter
CleanUp code. remove all notUsable params

Implement HashSet instead ArrayList

**Comment by Serduk** [comment]
Done.
How you can check it:
Go to Question list and scroll down and app.
Current build should work faster than previous (This point hard check)

**Comment by inndunas** [comment]
checked in 1.2.1
