### ISSUE TITLE
Major: Game Activity: Add round sound in each 12 questions

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#55]
Sound should be played on 12, 24 and 36 question
Sound should be taken from raw (Basic WWW sounds)

**Comment by Serduk** [comment]
Fixed in 1.0.1
git commit: f20bbf5..351eba4

**Comment by inndunas** [comment]
@Serduk 
checked in 1.1.0 build.
FYI: sound is played after tap on "answer" but isnt when user skips the question
