### ISSUE TITLE
CRITICAL: Menu header: button "back" always returns user to main menu

### ISSUE THREAD

**Issue by inndunas** [Serduk/whatWhereWhen#57]
**Descriptions:** 
Button "back" in menu header always returns user to main menu screen instead of previous screen

**Environment:** 
0.0.7 build

**STR:** 
1. open app
2. go to questions activity
3. go to questions list
4. tap on button "back" in menu header

**Actual result:**
user was returned to the main menu

**Expected result:**
user was returned to the question activity

**Comment by Serduk** [comment]
Fixed by using this method:

`
    @Override
    public boolean onSupportNavigateUp(){
        onBackPressed();
        return true;
    }
`

**Comment by Serduk** [comment]
fixed in 1.0.0

**Comment by inndunas** [comment]
@Serduk 
checked in 1.0.0. build
