### ISSUE TITLE
CRITICAL: Questions list: selected check-boxes are duplicated when more than 1 screen with questions is avalaible

### ISSUE THREAD

**Issue by inndunas** [Serduk/whatWhereWhen#62]
**Descriptions:** 
Marked as selected check-boxes of questions are duplicated when more than 1 screen with questions is avalaible (scrolled down).

**Environment:**
0.0.7 build

**Pre-conditions:**
1. app is launched
2. more than 20 questions are uploaded

**STR:**
1. go to Questions activity
2. go to questions list
3. tap on check-box of one question

**Actual result:**
one question on every screen was marked as selected

**Expected result:**
only one choosed question was marked as selected

**Comment by Serduk** [comment]
Fixed in 0.0.8 build

**Comment by inndunas** [comment]
@Serduk 
checked in 0.0.9 build
