### ISSUE TITLE
CRITICAL: Game activity: app's crash after tap on "random game"

### ISSUE THREAD

**Issue by inndunas** [Serduk/whatWhereWhen#65]
**Descriptions:**
Application crashed after trying to start random game

**Environment:**
0.0.8 build

**STR:**
1. launch app
2. go to game activiry
3. start new random game

**Actual result:**
app crushed

**Expected result:**
user see message that there are no questions for random game

**Comment by inndunas** [comment]
@Serduk 
**UPD:** problem also exists when some questions were uploaded to game

**STR:** 
1. upload questions
2. start new random game

**Actual result:** 
app was crushed

**Expected result:**
new random game was started

**Comment by Serduk** [comment]
fixed.

Also, fixed bug where customer can't start game without custom questions

**Comment by inndunas** [comment]
@Serduk checked in 0.0.9 build.
