### ISSUE TITLE
Major: Questions List activity: absent questions: Wrong Text in header

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#67]
Wrong text in header if absent questions in DB

![image](https://user-images.githubusercontent.com/2543139/38984309-025d8244-43cf-11e8-94f9-17bd6b622bc4.png)

**Comment by Serduk** [comment]
fixed in 1.0.0
https://monosnap.com/file/ds2CN2cwIe3bpPye06mk5R36pggZcJ

**Comment by inndunas** [comment]
@Serduk 
checked in 1.0.0
