### ISSUE TITLE
Major: Move all texts to String.xml

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#68]
Move all texts from code to string xml.

**Comment by Serduk** [comment]
will be fixed in few steps.
1st commit: created texts in xml 549fb88

**Comment by Serduk** [comment]
Fixed in 1.0.0

@inndunas , make sure, from FrontEnd side nothing not changed.
What i mean: all text should be stay and placed on their place.
if you will see some int instead of text -> it's bug of this issue

for example:

if you will see something like "123123786182734" instead text "Timer" -> this is a problem of this issue

**Comment by inndunas** [comment]
checked in 1.0.0 build
