### ISSUE TITLE
Major: BE: Add column with array of played questions to user table

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#69]
Add column with array of played questions to user table

Column should have String data with array of ID's of played questions
This data will be shown in played history

Story:
1. User complete one of game
2. user go to palyed history
3. User tap on one of the game in history
4. User should see win/lose rating/ date of game/ list of played questions in that session

**Comment by Serduk** [comment]
This issue is backend part and already Implemented in #37 
UI part (front end) will be implemented #80 

How you can check it:
1. app don't crashed after start.
2. Played history displayed correctly

**Comment by inndunas** [comment]
@Serduk 
checked in 1.2.0 build.
