### ISSUE TITLE
CRITICAL: Game activity: non-active button "back" in new game presetting

### ISSUE THREAD

**Issue by inndunas** [Serduk/whatWhereWhen#70]
**Decription:**
User can not come back to main screen from new game presetting.
**Environment:**
0.0.9 build
**STR:**
1. launch app
2. tap on "start game"
3. tap on button "back"

**Actual result:**
user stays on game presettings screen
**Expected result:**
user comes back to main screen

**Comment by Serduk** [comment]
commit: d5b7491..971bf4b 
Fixed in 1.0.1

**Comment by inndunas** [comment]
@Serduk 
checked in 1.1.0 build.
