### ISSUE TITLE
MAJOR: Game activity: timer doesn't stop when user exits the game

### ISSUE THREAD

**Issue by inndunas** [Serduk/whatWhereWhen#71]
**Descriptions:**
Minute's timer doesn't stop when user exits the game, it works and sounds till minute ends
**Environment:**
0.0.9 build

**Preconditions:**
1. app is launched
2. any questions are uploaded

**STR:**
1. start new game (any random or custom)
2. leave this game 

**Actual result:**
Game was closed but timer still works and user listens it's sound in 50 seconds and 1 minute
**Expected result:**
Game was closed and timer was stopped.

**Comment by Serduk** [comment]
Fixed in 3634625

Sound should be stoped after:
App destroying
exit confirming from dialog in game activity

**Comment by inndunas** [comment]
@Serduk 
checked in 1.1.0 build
