### ISSUE TITLE
MAJOR: Questions activity: add avalaibility to delete questions from questions list

### ISSUE THREAD

**Issue by inndunas** [Serduk/whatWhereWhen#72]
User story:
1. User goes to questions list
2. User marks any questions taping on the checkbox 
3. User taps on button "delete questions" or smth similiar
-------------------
All marked questions are fully removed from questions list and app.

**Comment by Serduk** [comment]
Fixed in  cd6d70b..434a3a8

**Comment by inndunas** [comment]
checked in 1.2.1
