### ISSUE TITLE
Critical: Fix Warnings which displayed on build compilation

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#74]
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.

**Comment by Serduk** [comment]
Updated dependencies in gradle
https://monosnap.com/file/qZ1Jz5JiW8sPYJ5qsxx4Tvo508WjpZ

How we can test it:
check start app, upload questions
play custom game,
 play random quesitons

**Comment by inndunas** [comment]
checked in 1.0.0 build
