### ISSUE TITLE
Major: App version displaying: wrong displaying in few places

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#75]
In app and in app preferences on real device different app version:

https://monosnap.com/file/luog4ks9JGBeOyNWVYsaGKwyqAzpWZ
https://monosnap.com/file/45t7HixAg81QcH4uqrvSjbb4Yrg7Ba

**Comment by Serduk** [comment]
fixed in b88fa1a

**Comment by inndunas** [comment]
@Serduk 
checked in 1.0.0
