### ISSUE TITLE
Critical: Questions List Activity: wrong count of games after scrolling in few places

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#76]
https://monosnap.com/file/9DfT1APpDIntpOaxbaXYxT6lKZBlwU

**STR:**
1. Mark few questions in top
2. mark few questions in bottom
3. clear all questions
4. go to top

**Comment by Serduk** [comment]
Fix in 1.2.0
commit: c20e850

I'm just remove List, and each time cal DB and get size of selected qustions from DB

**Comment by inndunas** [comment]
@Serduk 
checked in 1.2.0 build, problem still exists.

**Comment by Serduk** [comment]
Fixed in 1.2.1

**Comment by inndunas** [comment]
checked in 1.2.1
