### ISSUE TITLE
Major: BE: File Reader: Refactoring and optimize

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#77]
Performance improvement
init 1 string instead of 3 diff using

question.setQuestion(currentLine.split(separator)[1]);
question.setAnswer(currentLine.split(separator)[2]);
question.setDifficulty(currentLine.split(separator)[3]);

**Comment by Serduk** [comment]
Just make sure -> you can upload files

**Comment by Serduk** [comment]
6843e76

**Comment by inndunas** [comment]
checked in 1.0.0
