### ISSUE TITLE
Critical: All questions activity: Display all questions

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#8]
Prepare query for room
display all questions in questions list

**Comment by Serduk** [comment]
examples how solvin this questions:

`http://www.vogella.com/tutorials/AndroidListView/article.html`
`https://github.com/Serduk/starbuzz/tree/master/app/src/main`

**Comment by Serduk** [comment]
Fixed in 0.0.7

if you tap on this question -> you will get to new activity with details about this question

**Comment by inndunas** [comment]
@Serduk 
checked in 0.0.7 build
