### ISSUE TITLE
LOW: Game activity: non-correct counting of W/L/Skipped persents on game info screen

### ISSUE THREAD

**Issue by inndunas** [Serduk/whatWhereWhen#83]
**Descriptions:** 
Counting of W/L/Skipped persents on game info screen is totally non-correct
**Environment:**
1.1.0 build
**Preconditions:** 
app launched
**STR:** 
1. start new random game
2. answer correct for 2 questions, wrong for 4 questions, skip 30 questions
**Actual result:**
Game info screen with next persents is shown:
Win: 5%
Lose: 65%
Skipped: 30%
**Expected result:**
Win: 5,555555..%
Lose: 11.11111..%
Skipped: 83,33333..%
**Attachments:**
Screenshot with persent counting
![whatsapp image 2018-05-21 at 00 46 36](https://user-images.githubusercontent.com/38105828/40284025-c3d80cbc-5c90-11e8-8755-7fa99de9fc00.jpeg)

**Comment by Serduk** [comment]
fix: a425506
Fixed in 1.1.1 and above

**Comment by inndunas** [comment]
UPD: in this case W/L/S percents should be 6/11/83 instead of current 5/15/80

**Comment by Serduk** [comment]
Seems like fixed. Please, recheck it

**Comment by inndunas** [comment]
@Serduk 
checked in 1.2.1, fixed.
