### ISSUE TITLE
MAJOR: Questions activity: Sorting questions on difficulty is applied only for 1st number of difficulty value

### ISSUE THREAD

**Issue by inndunas** [Serduk/whatWhereWhen#85]
**Descriptions:** 
Sorting questions on difficulty is applied only for 1st number of difficulty value (e.g. diff 12 is easier than 2). 
**Environment:**
Build 1.1.0
**Preconditions:**
App lauched
Question's file with difficulty values 1, 2, 3, 12, 13 is uploaded
**STR:**
1. Go to questions list
2. Tap on sorting -> easiest first

**Actual result:**
Questions sorted: 1, 12, 13, 2, 3
**Expected result:**
Questions sorted by difficulty: 1, 2, 3, 12, 13

**Comment by inndunas** [comment]
@Serduk 
suspect that problem is caused by non-proper format of data saving: string instead of number.
also when in .txt file difficulty isn't the number - value of difficulty on questions list should be empty

**Comment by Serduk** [comment]
Fixed
Commit: 01c8cfc
Build: 1.2.0

![image](https://user-images.githubusercontent.com/2543139/40427280-e75fe88c-5ea5-11e8-9702-259ce5950aca.png)

**Comment by inndunas** [comment]
@Serduk 
checked in 2.0, fixed
