### ISSUE TITLE
MAJOR: Questions activity: 3 different alerts are shown when user uploads empty questions file 

### ISSUE THREAD

**Issue by inndunas** [Serduk/whatWhereWhen#87]
**Descriptions:**
3 different alerts are shown when user uploads empty questions file 
**Environment:**
1.1.0 build
**Preconditions:**
app launched
empty .txt file is avalaible on device
(you can use this file https://drive.google.com/open?id=1Te_rjtxA7qJBRSShRBG-7bnjNtwai6bC)
**STR:**
Go to questions menu
Tap on "upload questions from local files"
Upload empty .txt file
**Actual result:**
Alert with text: "File reading problem" is shown
Alert with text: "File is empty" is shown
Alert with text: "Something wrong with file" is shown
**Expected result:**
Alert with text: "File is empty" is shown

**Comment by inndunas** [comment]
@Serduk 
this issue is closely linked with #86

**Comment by Serduk** [comment]
Commit: 9754a6a
Fixed in 1.2.0

@inndunas , I need your help in debuging this issue.
I can't repro on my env, but seems this issue fixed.
Please, see my app for checking this issue bellow. 
If everything ok -> move to "Pending on Build"


[app-debug.apk.zip](https://github.com/Serduk/whatWhereWhen/files/2031729/app-debug.apk.zip)

**Comment by inndunas** [comment]
@Serduk 
checked, now 2 alerts are showm instead 3
there are "File reading problem" and "File is empty"

**Comment by Serduk** [comment]
Fix:
commit: 9513ed3

Now: 
If problem with file: "Something Wrong with file"
If file is empty: "Empty File"

**Comment by inndunas** [comment]
@Serduk checked in 1.2.0, fixed for empty file

**Comment by Serduk** [comment]
seems like fixed for me.
If problem still reproducible -> please, let me know
