### ISSUE TITLE
LOW: Questions list: add loading сircle while user changes type of questions sorting

### ISSUE THREAD

**Issue by inndunas** [Serduk/whatWhereWhen#88]
User story:
1. user goes to questions list
2. user choose any type of sorting the questions
3. user choose another type of sorting the questions
-------------
Loading сircle is shown before the questions list while sorting is in progress (even if it continues very short period of time)

**Comment by Serduk** [comment]
Commit: 7b529b4

How you can check it: Upload over 10k questions


![image](https://user-images.githubusercontent.com/2543139/41346707-157c29f4-6f10-11e8-8857-2723e1ef58f6.png)

**Comment by Serduk** [comment]
For this part of questions:
(even if it continues very short period of time)

how long should be displayed?
Please create another issue for this task (if more than 1 sec)

**Comment by inndunas** [comment]
checked in 1.2.1
