### ISSUE TITLE
Major: All questions screen: add sorting for questions

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#9]
Add sorting for all questions
Sorting by:
Data Upload
Difficult of questions
Answered/Not Answered

**Comment by Serduk** [comment]
commit with fix: 56f3d3e

**Comment by Serduk** [comment]
fixed and implemented in 1.0.1

**Comment by inndunas** [comment]
@Serduk 
checked in 1.1.0 build
Sorting by data upload and difficult of questions exists and works, but sorting for answered/not answered doesnt exists.
Please, inform me if you decided do not implement such type of sorting or if you will implement it later.

**Comment by inndunas** [comment]
@Serduk 
checked question sorting in 1.2.0 build, everything works.

conserning the problem with last slipped question - yes, it exists. I'll now submit new ticket of this issue.
