### ISSUE TITLE
Major: game activity: add skipped

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#90]
Add Skipped questions count to game acitivity

Need discuss UI with @inndunas

**Comment by inndunas** [comment]
@Serduk 
checked in 1.2.1 build
there are no skipped questions counter in game activity, only in finish game screen. 
please, add it to game activity too. 

![screenshot_20180726-221546 1](https://user-images.githubusercontent.com/38105828/43283633-19a67da2-9122-11e8-9e9e-fb89e5800d50.png)
![screenshot_20180726-221911](https://user-images.githubusercontent.com/38105828/43283634-19c5c040-9122-11e8-9307-88cf4129b406.png)

**Comment by Serduk** [comment]
fixed

![image](https://user-images.githubusercontent.com/2543139/43746077-c1c47374-99ea-11e8-89b2-c91d58a21057.png)

**Comment by inndunas** [comment]
@Serduk checked, everything is OK
