### ISSUE TITLE
Major: Played History: Latest played game should be displayed first

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#92]
![image](https://user-images.githubusercontent.com/2543139/40553366-134b0ebc-604b-11e8-8a59-e0642b27354c.png)

Sort history by date.
Latest games should be displayed first (upper)

**Comment by Serduk** [comment]
Commit: 725d7fc
Fixed in 1.2.0

**Comment by inndunas** [comment]
@Serduk 
checked in 1.2.0.
