### ISSUE TITLE
BLOCKER: Game result: app crashed after tapping on "show all results"

### ISSUE THREAD

**Issue by inndunas** [Serduk/whatWhereWhen#95]
**Descriptions:**  
App crashes after tapping on "show all results" at the game result screen
**Enviroment:**
1.2.0 build
**Preconditions:**
App launched
**STR:**
1. Fully play any game - random or custom
2. On the game result screen tap on buttom "Show all results"

**Actual result:** 
App crashed
**Expected result:**
Screen with all games statistics is shown 
**Attachments:** 
Crash alert
![crash](https://user-images.githubusercontent.com/38105828/41613988-db6173d8-73ff-11e8-9211-ba37f625ffe3.png)

**Comment by Serduk** [comment]
fixed in 1.2.1

**Comment by inndunas** [comment]
checked in 1.2.1
