### ISSUE TITLE
CRITICAL: Game activity: when the last question of the game is skipped - it is not marked as skipped in game result

### ISSUE THREAD

**Issue by inndunas** [Serduk/whatWhereWhen#97]
**Description:** 
When the last question of the game is skipped - it is not marked as skipped in game result and W/L/Skipped percents are not correctly counted
**Environment:**
Build 1.2.0
**Preconditions:**
App is lauched
**STR:**
1. Start new game (any random or custom)
2. Answer all question excluding last one
3. Skip last question

**Actual result:**
1. Skipped question is not marked as skipped in the game result screen
2. Percents of W/L/Skipped are not correctly counted (Skipped is counted as loose)

**Expected result:**
1. Skipped question is marked as skipped in the game result screen
2. Percents of W/L/Skipped are correctly counted (Skipped is counted as skipped)

**Attachment:**
Game result screen
![skipped last question](https://user-images.githubusercontent.com/38105828/41625933-44757018-7423-11e8-877f-c11a26d9c86d.png)

**Comment by Serduk** [comment]
fixed in 1.2.1

**Comment by inndunas** [comment]
checked in 1.2.1
